### PR TITLE
Generate code coverage metrics and upload to codecov.io

### PR DESCRIPTION
**Pull request by Liamsi**
- add grcov to circleci and upload coverage metrics to codecov.io

- add cargo audit while at it

Preferably we merge this before other PRs.

### CODE REVIEW

**Comment by marbar3778** [comment]
is there a preference to stay with circle? with github actions its a bit nicer since it is all in one place and it has nice support for rust. 

If people want to go to one location for ci and code (github) I can make a follow-up PR to transfer over to GA

**Comment by Liamsi** [comment]
I'm OK with switching to github actions. They look very cool. I didn't look into them that much yet. I mostly chose to not dig deeper as it seemed all the go-repos are still using circle and not really gh-actions? I think circle is mostly used because of performance and configurability.

Would you use this grcov support then? https://github.com/actions-rs/grcov)

**Comment by Liamsi** [comment]
I'll try to figure out why the test coverage reports 0% first :-D If others agree to switch to gh-Actions, I think it would be a good move. Any opinions cc @ebuchman @greg-szabo @xla?

**Comment by Liamsi** [comment]
Since the last commit we the total coverage (finally)... I'll cleanup the config in a bit and then we can merge.

**Pull request merged**
