### PR TITLE
Upgrade to hyper v0.13; use async/await

### PR DESCRIPTION
**Pull request by tony-iqlusion**
The crate itself builds with these changes, but the tests don't.

I'm not sure how to write tests for this (it's my first time using `async`/`await` in Rust 😅)

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
I tried the obvious thing (and what I'd do in TypeScript): add `async` to my tests. Unfortunately...

```
error: async functions cannot be used for tests
```

**Comment by tony-iqlusion** [comment]
Well, I got it to compile locally, but the tests don't run:

```
---- rpc::net_info stdout ----
thread 'rpc::net_info' panicked at 'no current reactor', /Users/bascule/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21
```

**Comment by Liamsi** [comment]
I briefly looked into `#[tokio::test]` but it seams that the whole body of the test would needs to be async (which isn't the case for the current integration tests). 

Instead I got sth like this working locally:

```rust
mod rpc_asyc {
    use tendermint::rpc::Client;
    use tokio::runtime::Builder;
    use core::future::Future;

    fn block_on<F: Future>(future: F) -> F::Output {
        Builder::new()
            .basic_scheduler()
            .enable_all()
            .build()
            .unwrap()
            .block_on(future)
    }
    
    #[test]
    fn my_test() {
        let cli = block_on(Client::new(&"tcp://127.0.0.1:26657".parse().unwrap())).unwrap();
        let net_info = block_on(cli.net_info()).unwrap();
        assert!(net_info.listening);
    }
}
```

**Comment by Liamsi** [comment]
FWIW I created a PR against your branch with minimal changes here: #87 (feel free to ignore/close it if you settle with another aproach)

**Comment by tarcieri** [comment]
Cool, I merged #87 into this branch. It appears to be working 🎉 

I think it might be worth fixing the HTTP error handling too, which I'll take a quick stab at

**Comment by tony-iqlusion** [comment]
Added some basic non-panicking HTTP error handling in a50b503.

Unfortunately I don't have a local Tendermint to test against at the moment so I'm not sure it actually works. @Liamsi were the tests passing locally for you?

After `cosmoshub-3` launches I'll give it a try against that.

**Comment by Liamsi** [comment]
>  @Liamsi were the tests passing locally for you?

Most of the integration tests pass but passed two didn't  (`abci_info`, `genesis`). 
- genesis fails with: called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("invalid digit found in string at line 11 column 26") }
 - abci_info with: called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("missing field `last_block_height` at line 9 column 5") }

**Comment by tony-iqlusion** [comment]
@Liamsi aah cool, well I'm guessing those weren't regressions then, so at least we're no worse off.

Can you approve this PR if you think it looks good?

**Comment by Liamsi** [comment]
Yes, I think it's OK to fix those regressions in another PR.

**Pull request merged**
