### PR TITLE
Remove secret_connection and ring dependency

### PR DESCRIPTION
**Pull request by yihuang**
I just upgraded the ring dependency, changed ``secret_connection.rs`` accordingly, hope you like it.
We are using ``tendermint-rs`` in our project, there are probably a few PRs following this one ;D

### CODE REVIEW

**Comment by tarcieri** [comment]
Note that per #27 I thought the plan was to move Secret Connection back to the KMS repo (in which case the Secret Connection impl in this crate should just be deleted).

Are you actually using Secret Connection via this crate?

In the KMS repo, I moved the ([re-vendored](https://github.com/tendermint/kms/pull/365)) Secret Connection implementation over to the `chacha20poly1305` crate:

https://github.com/tendermint/kms/pull/366

**Comment by yihuang** [comment]
Good to know that, we don't use secret_connection. We upgrade this only because the version of ring conflicts with our dependencies. I would love to see it removed ;D

**Comment by tarcieri** [comment]
@yihuang are you experiencing that conflict even when the `secret-connection` feature is disabled?

But yeah, `ring-asm` conflicts are super annoying, which is why I'd like to get rid of *ring*, especially considering we only use it for ChaCha20Poly1305.

**Comment by yihuang** [comment]
I don't see optional dependencies in git master version of ``tendermint-rs``, I was not looking at the most recent version?

**Comment by tarcieri** [comment]
@yihuang all of the cargo features were removed in the git master (with the goal of splitting things up into different crates)

The latest release (sans a point release to re-export `signatory`) is at:

https://github.com/interchainio/tendermint-rs/tree/v0.10.0

`secret-connection` is opt-in, so I'd be surprise if you saw *ring* conflicts unless you specifically activated it.

**Comment by yihuang** [comment]
Thanks, I see. But I think we will stick to the git version anyway because we want to work on the lite client implementation.

**Comment by tarcieri** [comment]
Aha! Ok

There seems to be a bit of confusion around #27, but I think the plan is still to continue Secret Connection work in the KMS repo, in which case I'd suggest deleting the implementation in this repo.

**Comment by yihuang** [comment]
So I just changed the commit to remove secret_connection and related dependencies(hope I've got them all).

**Comment by Liamsi** [comment]
> looks like CI may not be running?

Looks like all PRs coming from forks (not branches in this repo) do not trigger CI.

**Comment by tarcieri** [comment]
@Liamsi weird, wonder why #66 is green. It'd be nice to merge this one.

**Comment by Liamsi** [comment]
🤔 I think #66 is green because it seems CI is not required for this branch (interchainio:lite_impl_simple_merkle_merged)? Also noteworthy: I could merge #36 even without an approving review.  (master seems to require an approving review and CI in case it comes from a branch). I suspect that if you approve this PR it can be merged; I guess CI would then run on merge.

**Comment by yihuang** [comment]
Do I need to re-commit with PGP signing on?

**Comment by tarcieri** [comment]
@yihuang looks like it. can you give that a try?

**Comment by Liamsi** [comment]
I agree, it could unblock merging this (hopefully). I think I've already merged a few of @yihuang's PRs into my branch (apparently GPG signed commits aren't required there). Hope we won't have to redo those too 🤞

**Comment by yihuang** [comment]
Re-commited with pgp signing, also removed `tendermint/tests/secret_connection.rs`.

**Comment by tarcieri** [comment]
Still saying it's waiting for GPG status to be reported 😢 

@ebuchman any idea what's up with the GPG check? It seems to be rejecting GPG signed commits.

Also, are you sure you *really* want GPG signed *commits*? (as opposed to e.g. GPG signed tag objects for releases). See:

https://mikegerwitz.com/2012/05/a-git-horror-story-repository-integrity-with-signed-commits

**Comment by Liamsi** [comment]
I'd also vouch for signing releases / tags only.

**Comment by Liamsi** [comment]
Not sure what is going on here. Now all commits are signed but GPG still shows up as "expected". Similarly for #59.

**Comment by Liamsi** [comment]
Thanks @greg-szabo!

**Comment by Liamsi** [comment]
OK, CI doesn't run on forks but the GPG issue is resolved. Will merge now. Thanks again @yihuang :-)

**Pull request merged**
